# Generated by Django 3.1 on 2020-09-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0002_ranshorturl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ranshorturl',
            new_name='anoshort',
        ),
    ]
