# Generated by Django 3.1 on 2020-09-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0003_auto_20200926_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='anoshort',
        ),
    ]
