# Generated by Django 3.1 on 2020-10-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0004_delete_anoshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='session_key',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
